# HTTP Server
server:
  port: 8001   # HTTP (Tomcat) port

# Spring properties
spring:
  application:
     name: accounts-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
